// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortfolioApi.Data;

#nullable disable

namespace PortfolioApi.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    partial class PortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortfolioApi.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GithubUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LiveUrl")
                        .HasColumnType("text");

                    b.Property<string[]>("Technologies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 30, 8, 5, 35, 63, DateTimeKind.Utc).AddTicks(7225),
                            Description = "Developed automation scripts for server deployment and network configuration in large-scale data center environments. Reduced deployment time by 40% and minimized human error.",
                            ImageUrl = "https://static.prod-images.emergentagent.com/jobs/6873ee99-1441-48fe-ae88-ccaafe02c125/images/4c21638db175ad02b5fc66c46c68486633cec27c3788c915b792294b67300223.png",
                            Technologies = new[] { "Python", "Bash", "Linux", "Network Automation" },
                            Title = "Data Center Infrastructure Automation"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 30, 8, 5, 35, 63, DateTimeKind.Utc).AddTicks(7231),
                            Description = "Built a real-time network monitoring dashboard for tracking data center performance metrics, system health, and incident alerts. Integrated with multiple data sources for comprehensive visibility.",
                            ImageUrl = "https://static.prod-images.emergentagent.com/jobs/6873ee99-1441-48fe-ae88-ccaafe02c125/images/f2c56b726d38cdfccb6bbb9eba396241d5d178d36b78b0b7f365892d672ba159.png",
                            Technologies = new[] { "React", "TypeScript", "Node.js", "PostgreSQL" },
                            Title = "Network Monitoring Dashboard"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 30, 8, 5, 35, 63, DateTimeKind.Utc).AddTicks(7234),
                            Description = "Created a full-stack application to track server hardware lifecycle, maintenance schedules, and asset management. Improved operational efficiency and preventive maintenance planning.",
                            ImageUrl = "https://static.prod-images.emergentagent.com/jobs/6873ee99-1441-48fe-ae88-ccaafe02c125/images/c1750c90b3deb7c014fce746335daa20e6f30d44da47ca8af0b4bcdd592a56dc.png",
                            Technologies = new[] { "C#", "ASP.NET Core", "PostgreSQL", "React" },
                            Title = "Hardware Lifecycle Management System"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Programming Languages",
                            Level = 85,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Programming Languages",
                            Level = 90,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Programming Languages",
                            Level = 88,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Programming Languages",
                            Level = 85,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Programming Languages",
                            Level = 70,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Frontend",
                            Level = 90,
                            Name = "React"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Backend",
                            Level = 85,
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Backend",
                            Level = 82,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Database",
                            Level = 85,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Infrastructure",
                            Level = 92,
                            Name = "Linux"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Infrastructure",
                            Level = 95,
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 12,
                            Category = "DevOps",
                            Level = 80,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 13,
                            Category = "DevOps",
                            Level = 88,
                            Name = "Git"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
